const PDFDocument = require("pdfkit");
const { db } = require("../config/firebase");

/**
 * GET /api/vaccinations/download-certificate/:vaccinationId
 * Generates and downloads a vaccination certificate as a PDF.
 */
exports.downloadCertificate = async (req, res, next) => {
    try {
        const { vaccinationId } = req.params;
        const userId = req.user.uid;

        // 1. Fetch Vaccination Record
        const vaccDoc = await db.collection("vaccinations").doc(vaccinationId).get();

        if (!vaccDoc.exists) {
            return res.status(404).json({
                success: false,
                message: "Vaccination record not found",
                data: null
            });
        }

        const vaccData = vaccDoc.data();

        // 2. Check Ownership
        if (vaccData.userId !== userId) {
            return res.status(403).json({
                success: false,
                message: "Unauthorized: You can only download your own certificates",
                data: null
            });
        }

        // 3. Fetch User Details (for name)
        const userDoc = await db.collection("users").doc(userId).get();
        const userData = userDoc.exists ? userDoc.data() : { name: "Valued User" };

        // 4. Generate PDF
        const doc = new PDFDocument({ size: "A4", margin: 50 });

        // Stream the PDF directly to the response
        res.setHeader("Content-Type", "application/pdf");
        res.setHeader(
            "Content-Disposition",
            `attachment; filename=Certificate_${vaccData.vaccineName}.pdf`
        );

        doc.pipe(res);

        // Styling & Content
        doc
            .rect(20, 20, 555, 780)
            .lineWidth(2)
            .stroke("#2C3E50");

        doc
            .fontSize(25)
            .fillColor("#2C3E50")
            .text("VACCINATION CERTIFICATE", { align: "center" });

        doc.moveDown();
        doc.lineWidth(1).strokeColor("#BDC3C7").moveTo(50, 80).lineTo(545, 80).stroke();

        doc.moveDown(2);
        doc
            .fontSize(16)
            .fillColor("#000000")
            .text(`This is to certify that`, { align: "center" });

        doc.moveDown();
        doc
            .fontSize(22)
            .fillColor("#2980B9")
            .text(userData.name || "N/A", { align: "center", bold: true });

        doc.moveDown();
        doc
            .fontSize(16)
            .fillColor("#000000")
            .text(`has successfully received the vaccination for`, { align: "center" });

        doc.moveDown();
        doc
            .fontSize(20)
            .fillColor("#27AE60")
            .text(vaccData.vaccineName, { align: "center", bold: true });

        doc.moveDown(2);

        // Details Table-like layout
        doc.fontSize(12).fillColor("#34495E");
        const labelX = 100;
        const valueX = 300;
        let currentY = doc.y;

        const drawRow = (label, value) => {
            doc.text(label, labelX, currentY);
            doc.text(value, valueX, currentY);
            currentY += 25;
        };

        drawRow("Dose Number:", vaccData.doseNumber.toString());
        drawRow("Date Taken:", vaccData.dateTaken);
        drawRow("Hospital:", vaccData.hospitalName);
        drawRow("Status:", vaccData.status.toUpperCase());

        doc.moveDown(4);

        // Footer
        doc
            .fontSize(10)
            .fillColor("#7F8C8D")
            .text("Generated by Digital Vaccination Management System", { align: "center" });

        doc.text(new Date().toLocaleString(), { align: "center" });

        doc.end();

    } catch (error) {
        next(error);
    }
};
